version: 0.2

env:
  parameter-store:
    DIST_ID : "cloudfront_distid"

phases:
  install:
    commands:
      - echo "***************************************"
      - echo "******** Installing Bundler **************"
      - echo "***************************************"
      - gem install bundler
  pre_build:
    commands:
      - echo "***************************************"
      - echo "******** Running Bundle Install *******"
      - echo "***************************************"
      - bundle install
  build:
    commands:
      - echo "***************************************"
      - echo "******** Building Jekyll site *********"
      - echo "***************************************"
      - bundle exec jekyll build
  post_build:
    commands:
      - echo "***************************************"
      - echo "******** Uploading to S3 **************"
      - echo "***************************************"
      - aws s3 sync _site/ s3://khaledzaky.com --delete --acl public-read
      - echo "***************************************"
      - echo "**** Invalidate Cloudfront cache ******"
      - echo "***************************************"
      - aws cloudfront create-invalidation --distribution-id $DIST_ID --paths /blog /404.html /about* /css* /postimages* /img* /js* /index.html /feed.xml