version: 0.2

env:
  parameter-store:
    DIST_ID : "cloudfront_distid"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "***************************************"
      - echo "******** Installing dependencies ******"
      - echo "***************************************"
      - npm ci
  build:
    commands:
      - echo "***************************************"
      - echo "******** Building Astro site **********"
      - echo "***************************************"
      - npm run build
  post_build:
    commands:
      - echo "***************************************"
      - echo "******** Uploading to S3 **************"
      - echo "***************************************"
      - aws s3 sync dist/ s3://khaledzaky.com --delete --acl public-read
      - echo "***************************************"
      - echo "**** Invalidate Cloudfront cache ******"
      - echo "***************************************"
      - aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"