AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Blog Agent — AI-powered blog post research, drafting, and publishing pipeline

Parameters:
  NotificationEmail:
    Type: String
    Description: Email address for HITL draft review notifications
  GitHubRepo:
    Type: String
    Default: kzaky/khaledzaky.com
  GitHubBranch:
    Type: String
    Default: master
  BedrockModelId:
    Type: String
    Default: us.anthropic.claude-3-5-sonnet-20241022-v2:0
    Description: Bedrock model ID for research and drafting

Resources:

  # --- S3 Bucket for drafts ---
  DraftsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-drafts"
      LifecycleConfiguration:
        Rules:
          - Id: CleanupOldDrafts
            Status: Enabled
            ExpirationInDays: 90

  # --- SNS Topic for HITL notifications ---
  ReviewTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-review"

  ReviewSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ReviewTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

  # --- IAM Role for Lambda functions ---
  AgentLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-lambda-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource:
                  - "arn:aws:bedrock:*::foundation-model/*"
                  - !Sub "arn:aws:bedrock:*:${AWS::AccountId}:inference-profile/*"
                  - "arn:aws:bedrock:*::inference-profile/*"
              - Effect: Allow
                Action:
                  - aws-marketplace:ViewSubscriptions
                  - aws-marketplace:Subscribe
                Resource: "*"
        - PolicyName: S3DraftsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt DraftsBucket.Arn
                  - !Sub "${DraftsBucket.Arn}/*"
        - PolicyName: SNSPublish
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource: !Ref ReviewTopic
        - PolicyName: SSMGetParameter
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ssm:GetParameter
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/blog-agent/*"
        - PolicyName: StepFunctionsCallback
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:SendTaskSuccess
                  - states:SendTaskFailure
                Resource: "*"

  # --- Lambda Functions ---
  ResearchFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-research"
      Runtime: python3.12
      Handler: index.handler
      Code:
        ZipFile: |
          # Placeholder — deploy actual code from agent/research/index.py
          def handler(event, context):
              return {"error": "Deploy actual code"}
      Role: !GetAtt AgentLambdaRole.Arn
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          BEDROCK_MODEL_ID: !Ref BedrockModelId

  DraftFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-draft"
      Runtime: python3.12
      Handler: index.handler
      Code:
        ZipFile: |
          # Placeholder — deploy actual code from agent/draft/index.py
          def handler(event, context):
              return {"error": "Deploy actual code"}
      Role: !GetAtt AgentLambdaRole.Arn
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          BEDROCK_MODEL_ID: !Ref BedrockModelId

  NotifyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-notify"
      Runtime: python3.12
      Handler: index.handler
      Code:
        ZipFile: |
          # Placeholder — deploy actual code from agent/notify/index.py
          def handler(event, context):
              return {"error": "Deploy actual code"}
      Role: !GetAtt AgentLambdaRole.Arn
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref ReviewTopic
          DRAFTS_BUCKET: !Ref DraftsBucket
          APPROVE_URL: !GetAtt ApproveFunctionUrl.FunctionUrl

  ApproveFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-approve"
      Runtime: python3.12
      Handler: index.handler
      Code:
        ZipFile: |
          # Placeholder — deploy actual code from agent/approve/index.py
          def handler(event, context):
              return {"error": "Deploy actual code"}
      Role: !GetAtt AgentLambdaRole.Arn
      Timeout: 15
      MemorySize: 128

  ApproveFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt ApproveFunction.Arn
      AuthType: NONE

  ApproveFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApproveFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

  PublishFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-publish"
      Runtime: python3.12
      Handler: index.handler
      Code:
        ZipFile: |
          # Placeholder — deploy actual code from agent/publish/index.py
          def handler(event, context):
              return {"error": "Deploy actual code"}
      Role: !GetAtt AgentLambdaRole.Arn
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          GITHUB_REPO: !Ref GitHubRepo
          GITHUB_BRANCH: !Ref GitHubBranch
          GITHUB_TOKEN_PARAM: /blog-agent/github-token
          DRAFTS_BUCKET: !Ref DraftsBucket

  # --- Step Functions State Machine ---
  AgentStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-sfn-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource:
                  - !GetAtt ResearchFunction.Arn
                  - !GetAtt DraftFunction.Arn
                  - !GetAtt NotifyFunction.Arn
                  - !GetAtt PublishFunction.Arn
                  - !GetAtt ApproveFunction.Arn

  BlogAgentStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${AWS::StackName}-pipeline"
      RoleArn: !GetAtt AgentStateMachineRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "Blog Agent Pipeline: Research → Draft → HITL Review → Publish",
          "StartAt": "Research",
          "States": {
            "Research": {
              "Type": "Task",
              "Resource": "${ResearchFunction.Arn}",
              "ResultPath": "$.research_output",
              "Next": "Draft"
            },
            "Draft": {
              "Type": "Task",
              "Resource": "${DraftFunction.Arn}",
              "InputPath": "$.research_output",
              "ResultPath": "$.draft_output",
              "Next": "NotifyForReview"
            },
            "NotifyForReview": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke.waitForTaskToken",
              "Parameters": {
                "FunctionName": "${NotifyFunction.Arn}",
                "Payload": {
                  "title.$": "$.draft_output.title",
                  "slug.$": "$.draft_output.slug",
                  "categories.$": "$.draft_output.categories",
                  "description.$": "$.draft_output.description",
                  "markdown.$": "$.draft_output.markdown",
                  "date.$": "$.draft_output.date",
                  "taskToken.$": "$$.Task.Token"
                }
              },
              "ResultSelector": {
                "approved.$": "$.approved"
              },
              "ResultPath": "$.approval",
              "TimeoutSeconds": 604800,
              "Next": "CheckApproval"
            },
            "CheckApproval": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.approval.approved",
                  "BooleanEquals": true,
                  "Next": "Publish"
                }
              ],
              "Default": "Rejected"
            },
            "Publish": {
              "Type": "Task",
              "Resource": "${PublishFunction.Arn}",
              "Parameters": {
                "approved": true,
                "title.$": "$.draft_output.title",
                "slug.$": "$.draft_output.slug",
                "date.$": "$.draft_output.date"
              },
              "End": true
            },
            "Rejected": {
              "Type": "Succeed",
              "Comment": "Draft was rejected by reviewer"
            }
          }
        }

  # --- EventBridge Rule (optional scheduled trigger) ---
  # Uncomment to auto-trigger the agent on a schedule
  # ScheduledTrigger:
  #   Type: AWS::Events::Rule
  #   Properties:
  #     Name: !Sub "${AWS::StackName}-schedule"
  #     Description: "Weekly blog agent trigger"
  #     ScheduleExpression: "rate(7 days)"
  #     State: DISABLED
  #     Targets:
  #       - Arn: !Ref BlogAgentStateMachine
  #         Id: BlogAgentTarget
  #         RoleArn: !GetAtt EventBridgeRole.Arn
  #         Input: '{"topic": "Latest trends in cloud security"}'

Outputs:
  StateMachineArn:
    Description: ARN of the blog agent Step Functions state machine
    Value: !Ref BlogAgentStateMachine
  DraftsBucketName:
    Description: S3 bucket for draft storage
    Value: !Ref DraftsBucket
  SNSTopicArn:
    Description: SNS topic for review notifications
    Value: !Ref ReviewTopic
  HowToRun:
    Description: How to trigger the blog agent
    Value: !Sub |
      aws stepfunctions start-execution \
        --state-machine-arn ${BlogAgentStateMachine} \
        --input '{"topic": "Your blog topic here", "categories": ["cloud", "aws"]}'
